library:
  source-dirs: src
tests:
  senex-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - senex
    - hspec
copyright: 2019 Luis Borjas Reyes
maintainer: luis@lfborjas.com
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
dependencies:
- aeson-casing
- bytestring
- base >= 4.11 && < 10
- rio >= 0.1.8.0
name: senex
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Luis Borjas Reyes
github: lfborjas/senex
license: BSD3
executables:
  senex-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - senex
    - optparse-simple
description: Please see the README on Github at <https://github.com/lfborjas/senex#readme>
